import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

/// Badge style pilule (fond rose pâle, bordure et texte bordeaux) pour les
/// transactions créées automatiquement par le batch récurrent.
class AutoGeneratedBadge extends StatelessWidget {
  const AutoGeneratedBadge({super.key});

  static const Color _bg = Color(0xFFFFF5F6);
  static const Color _border = Color(0xFFE8B4BC);
  static const Color _text = Color(0xFF7A1F2E);

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
      decoration: BoxDecoration(
        color: _bg,
        borderRadius: BorderRadius.circular(999),
        border: Border.all(color: _border, width: 1),
      ),
      child: Text(
        'Automatique',
        style: GoogleFonts.poppins(
          fontSize: 11,
          fontWeight: FontWeight.w600,
          color: _text,
          height: 1.2,
        ),
      ),
    );
  }
}
